version: "3.9"

services:
  keycloak:
    image: "bitnami/keycloak:24.0.3"
    environment:
      KEYCLOAK_HTTP_PORT: "8080"
      KEYCLOAK_CREATE_ADMIN_USER: "true"
      KEYCLOAK_ADMIN: "admin"
      KEYCLOAK_PROXY: "edge"
      KEYCLOAK_ADMIN_PASSWORD: "admin"
      KEYCLOAK_DATABASE_HOST: "postgres"
      KEYCLOAK_DATABASE_USER: "postgres"
      KEYCLOAK_DATABASE_PASSWORD: "postgres"
      KEYCLOAK_DATABASE_NAME: "postgres"
      KEYCLOAK_DATABASE_PORT: "5432"
    depends_on:
      - "postgres"
    networks:
      - "cks-network"

  keycloak-config-cli:
    image: "bitnami/keycloak-config-cli:5.12.0"
    environment:
      KEYCLOAK_URL: "http://keycloak:8080"
      KEYCLOAK_USER: "admin"
      KEYCLOAK_PASSWORD: "admin"
      IMPORT_FILES_LOCATIONS: "/config/*"
    depends_on:
      - "keycloak"
    volumes:
      - "./keycloak/config.json:/config/config.json"
    networks:
      - "cks-network"

  nginx:
    image: "bitnami/nginx:1.25.5"
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - "./nginx/certs:/opt/bitnami/nginx/conf/bitnami/certs:ro"
      - "./nginx/server_blocks:/opt/bitnami/nginx/conf/server_blocks:ro"
    networks:
      - "cks-network"

  postgres:
    image: "bitnami/postgresql:15.6.0"
    environment:
      POSTGRESQL_USERNAME: "postgres"
      POSTGRESQL_PASSWORD: "postgres"
      POSTGRESQL_DATABASE: "postgres"
    ports:
      - "5432:5432"
    volumes:
      - "cks-postgres-data:/bitnami/postgresql"
    networks:
      - "cks-network"

  couchdb:
    image: "bitnami/couchdb:3.3.3"
    environment:
      COUCHDB_USER: "admin"
      COUCHDB_PASSWORD: "admin"
      COUCHDB_SECRET: "top-secret"
      COUCHDB_PORT_NUMBER: "7777"
    volumes:
      - "cks-couchdb-data:/bitnami/couchdb"
      - "./couchdb/10-config.ini:/opt/bitnami/couchdb/etc/local.d/10-config.ini"
    networks:
      - "cks-network"

  oauth2-proxy:
    image: "bitnami/oauth2-proxy:7.6.0"
    environment:
      OAUTH2_PROXY_EMAIL_DOMAINS: "oblivio.localhost"
      OAUTH2_PROXY_COOKIE_SECRET: "OQINaROshtE9TcZkNAm-5Zs2Pv3xaWytBmc5W7sPX7w="
      OAUTH2_PROXY_CLIENT_ID: "oauth2-proxy"
      OAUTH2_PROXY_CLIENT_SECRET: "72341b6d-7065-4518-a0e4-50ee15025608"
      OAUTH2_PROXY_UPSTREAMS: "https://couchdb.oblivio.localhost"
      OAUTH2_PROXY_PROVIDER: "oidc"
      OAUTH2_PROXY_PROVIDER_DISPLAY_NAME: "Keycloak"
      OAUTH2_PROXY_OIDC_ISSUER_URL: "http://keycloak:8080/auth/realms/master"
#      OAUTH2_PROXY_http_address = "0.0.0.0:4180"
#      OAUTH2_PROXY_cookie_secret = ""
#      OAUTH2_PROXY_email_domains = "oblivio.localhost"
#      OAUTH2_PROXY_cookie_secure = "false"
#      OAUTH2_PROXY_upstreams = "https://couchdb.oblivio.localhost"
#      OAUTH2_PROXY_cookie_domains = [".oblivio.localhost"]
#      OAUTH2_PROXY_whitelist_domains = [".oblivio.localhost"]
#      OAUTH2_PROXY_client_secret = "72341b6d-7065-4518-a0e4-50ee15025608"
#      OAUTH2_PROXY_client_id = "oauth2-proxy"
#      OAUTH2_PROXY_redirect_url = "https://oauth2-proxy.oblibio.localhost/oauth2/callback"
#      OAUTH2_PROXY_oidc_issuer_url = "https://keycloak.oblibio.localhost/auth/realms/master"
#      OAUTH2_PROXY_provider = "oidc"
#      OAUTH2_PROXY_provider_display_name = "Keycloak"
    networks:
      - "cks-network"

networks:
  cks-network:
    driver: "bridge"

volumes:
  cks-postgres-data:
    driver: "local"
  cks-couchdb-data:
    driver: "local"
